create table calendar_rezervari(
 id number(10) not null,
 punct_lucru_id number(10) not null,
 client_id number(10) not null,
 tip_rezervare_id number(10),
 data_ora date not null,
 validata varchar2(1) default 'N' not null,
 anulata varchar2(1) default 'N' not null,
 validata_de number(10),
 anulata_de number(10),
 mesaj varchar2(256),
 durata number(10),
 motiv_anulare varchar2(128),
 prezenta varchar2(1) default 'D' not null,
 rezervare_la number(10),
 creata_la date default sysdate not null,
 confirmata varchar2(1) default 'N' not null,
 validata_la date,
 confirmata_la date,
 anulata_la date,
 constraint calendar_rezervari_pk primary key (id),
 constraint calendar_rezervari_valid check (validata in ('D', 'N')),
 constraint calendar_rezervari_valid check (confirmata in ('D', 'N')),
 constraint calendar_rezervari_anul check (anulata in ('D', 'N')),
 constraint calendar_rezervari_prezent check (prezenta in ('D', 'N'))
);